apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:godel-rescheduler
rules:
- apiGroups:
  - "*"
  resources:
  - "customnoderesources"
  - "csinodes"
  - "poddisruptionbudgets"
  - "nmnodes"
  - "podgroups"
  - "schedulers"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  - "nodes"
  - "pods"
  - "movements"
  - "configmaps"
  - "deployments"
  - "affinitypsmgroups"
  - "cnrs"
  - "serviceprofiledescriptors"
  - "reservations"
  - "replicasets"
  - "statefulsets"
  - "statefulsetextensions"
  verbs:
  - "list"
  - "watch"
- apiGroups:
  - "*"
  resources:
  - "movements"
  verbs:
  - "get"
  - "create"
  - "delete"
- apiGroups:
  - "*"
  resources:
  - "movements/status"
  verbs:
  - "patch"
- apiGroups:
  - "*"
  resources:
  - "leases"
  verbs:
  - "get"
  - "create"
  - "update"
- apiGroups:
  - "*"
  resources:
  - "configmaps"
  verbs:
  - "get"
- apiGroups:
  - "*"
  resources:
  - "events"
  verbs:
  - "create"
- apiGroups:
  - "*"
  resources:
  - "pods/eviction"
  verbs:
  - "create"
