//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&GodelReschedulerConfiguration{}, func(obj interface{}) {
		SetObjectDefaults_GodelReschedulerConfiguration(obj.(*GodelReschedulerConfiguration))
	})
	return nil
}

func SetObjectDefaults_GodelReschedulerConfiguration(in *GodelReschedulerConfiguration) {
	SetDefaults_GodelReschedulerConfiguration(in)
}
