//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmConfig) DeepCopyInto(out *AlgorithmConfig) {
	*out = *in
	in.Args.DeepCopyInto(&out.Args)
	if in.CheckPolicies != nil {
		in, out := &in.CheckPolicies, &out.CheckPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmConfig.
func (in *AlgorithmConfig) DeepCopy() *AlgorithmConfig {
	if in == nil {
		return nil
	}
	out := new(AlgorithmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinPackingArgs) DeepCopyInto(out *BinPackingArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ResourceItems != nil {
		in, out := &in.ResourceItems, &out.ResourceItems
		*out = make([]ResourceItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinPackingArgs.
func (in *BinPackingArgs) DeepCopy() *BinPackingArgs {
	if in == nil {
		return nil
	}
	out := new(BinPackingArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BinPackingArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronjobTrigger) DeepCopyInto(out *CronjobTrigger) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronjobTrigger.
func (in *CronjobTrigger) DeepCopy() *CronjobTrigger {
	if in == nil {
		return nil
	}
	out := new(CronjobTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectorConfig) DeepCopyInto(out *DetectorConfig) {
	*out = *in
	in.Args.DeepCopyInto(&out.Args)
	if in.DetectorTrigger != nil {
		in, out := &in.DetectorTrigger, &out.DetectorTrigger
		*out = new(PolicyTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckPolicies != nil {
		in, out := &in.CheckPolicies, &out.CheckPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectorConfig.
func (in *DetectorConfig) DeepCopy() *DetectorConfig {
	if in == nil {
		return nil
	}
	out := new(DetectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GodelReschedulerConfiguration) DeepCopyInto(out *GodelReschedulerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
	out.ClientConnection = in.ClientConnection
	in.DebuggingConfiguration.DeepCopyInto(&out.DebuggingConfiguration)
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(ReschedulerProfile)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GodelReschedulerConfiguration.
func (in *GodelReschedulerConfiguration) DeepCopy() *GodelReschedulerConfiguration {
	if in == nil {
		return nil
	}
	out := new(GodelReschedulerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GodelReschedulerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupThrottleArgs) DeepCopyInto(out *GroupThrottleArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ThrottleItems != nil {
		in, out := &in.ThrottleItems, &out.ThrottleItems
		*out = make([]ThrottleItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupThrottleArgs.
func (in *GroupThrottleArgs) DeepCopy() *GroupThrottleArgs {
	if in == nil {
		return nil
	}
	out := new(GroupThrottleArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupThrottleArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingCheckerArgs) DeepCopyInto(out *PendingCheckerArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.PendingThresholds != nil {
		in, out := &in.PendingThresholds, &out.PendingThresholds
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefaultPendingThreshold != nil {
		in, out := &in.DefaultPendingThreshold, &out.DefaultPendingThreshold
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingCheckerArgs.
func (in *PendingCheckerArgs) DeepCopy() *PendingCheckerArgs {
	if in == nil {
		return nil
	}
	out := new(PendingCheckerArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PendingCheckerArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyTrigger) DeepCopyInto(out *PolicyTrigger) {
	*out = *in
	if in.CronjobTriggers != nil {
		in, out := &in.CronjobTriggers, &out.CronjobTriggers
		*out = make([]CronjobTrigger, len(*in))
		copy(*out, *in)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(string)
		**out = **in
	}
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyTrigger.
func (in *PolicyTrigger) DeepCopy() *PolicyTrigger {
	if in == nil {
		return nil
	}
	out := new(PolicyTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReschedulerPolicy) DeepCopyInto(out *ReschedulerPolicy) {
	*out = *in
	if in.PolicyTrigger != nil {
		in, out := &in.PolicyTrigger, &out.PolicyTrigger
		*out = new(PolicyTrigger)
		(*in).DeepCopyInto(*out)
	}
	in.Detector.DeepCopyInto(&out.Detector)
	in.Algorithm.DeepCopyInto(&out.Algorithm)
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FailureRatioThreshold != nil {
		in, out := &in.FailureRatioThreshold, &out.FailureRatioThreshold
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReschedulerPolicy.
func (in *ReschedulerPolicy) DeepCopy() *ReschedulerPolicy {
	if in == nil {
		return nil
	}
	out := new(ReschedulerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReschedulerProfile) DeepCopyInto(out *ReschedulerProfile) {
	*out = *in
	if in.PSM != nil {
		in, out := &in.PSM, &out.PSM
		*out = new(string)
		**out = **in
	}
	if in.IDCName != nil {
		in, out := &in.IDCName, &out.IDCName
		*out = new(string)
		**out = **in
	}
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.Tracer != nil {
		in, out := &in.Tracer, &out.Tracer
		*out = new(string)
		**out = **in
	}
	if in.ReschedulerPolicyConfigs != nil {
		in, out := &in.ReschedulerPolicyConfigs, &out.ReschedulerPolicyConfigs
		*out = make([]ReschedulerPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReschedulerProfile.
func (in *ReschedulerProfile) DeepCopy() *ReschedulerProfile {
	if in == nil {
		return nil
	}
	out := new(ReschedulerProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceItem) DeepCopyInto(out *ResourceItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceItem.
func (in *ResourceItem) DeepCopy() *ResourceItem {
	if in == nil {
		return nil
	}
	out := new(ResourceItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdTrigger) DeepCopyInto(out *ThresholdTrigger) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdTrigger.
func (in *ThresholdTrigger) DeepCopy() *ThresholdTrigger {
	if in == nil {
		return nil
	}
	out := new(ThresholdTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottleArgs) DeepCopyInto(out *ThrottleArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ThrottleItems != nil {
		in, out := &in.ThrottleItems, &out.ThrottleItems
		*out = make([]ThrottleItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottleArgs.
func (in *ThrottleArgs) DeepCopy() *ThrottleArgs {
	if in == nil {
		return nil
	}
	out := new(ThrottleArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThrottleArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottleItem) DeepCopyInto(out *ThrottleItem) {
	*out = *in
	out.ThrottleDuration = in.ThrottleDuration
	if in.CanBePreempted != nil {
		in, out := &in.CanBePreempted, &out.CanBePreempted
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottleItem.
func (in *ThrottleItem) DeepCopy() *ThrottleItem {
	if in == nil {
		return nil
	}
	out := new(ThrottleItem)
	in.DeepCopyInto(out)
	return out
}
